### ISSUE TITLE
Weird handheld lighting issues with water

### ISSUE THREAD

**Issue by supsm** [spiralhalo/LumiLights#22]
I've accidentally found that handheld light sources are very bright on water.
![2020-12-20_18 07 11](https://user-images.githubusercontent.com/60897356/102732020-558ebe80-42ee-11eb-803b-f3177a5cc2b3.png)
![2020-12-20_18 09 23](https://user-images.githubusercontent.com/60897356/102732095-9be41d80-42ee-11eb-8d02-255164c5ebd7.png)
![2020-12-20_18 07 13](https://user-images.githubusercontent.com/60897356/102732022-56bfeb80-42ee-11eb-9feb-d7f49f0e9812.png)

**Comment by supsm** [comment]
I forgot to mention that I was on v0.3 (not sure if 0.4 will make a difference)

**Comment by spiralhalo** [comment]
This bug is very weird. By chance did you switch between HDR and PBR version in the same session? Is the bug persistent or does it go away when you restart minecraft?

Currently I can't reproduce it reliably. Last time I encountered it, restarting minecraft fixed it. It's as if the bug is within minecraft, or the GL states, not sure. No error messages or anything.

If you found a hint to reliably reproduce it, please let me know.

**Comment by supsm** [comment]
I think I switched from Lumi HDR to Lumi PBR. I think I switched, then disconnected (but didn't close minecraft), then got on and found the bug. I'll do some more experiments when I have time later.

**Comment by spiralhalo** [comment]
The water wave generation in PBR and HDR are *very slightly* different, so that might be causing problem if the resource loader somehow mix them up. It should no longer be an issue in unified version since the water wave  generation *should* be identical.

**Comment by spiralhalo** [comment]
For the time being, since it can only be reproduced via external force (switching resource packs) there isn't much I can do about it other than make people switch to unified.

If the problem persists in unified version (e.g. when turning PBR on/off in unified) or if there are other ways to reproduce this issue without switching resource pack, then please reopen the issue.

Meanwhile I won't stop you from commenting on this issue if you have related discussion. Thanks again for the report.

**Comment by supsm** [comment]
Would this be a canvas issue then? Should I report this in the canvas repo?

**Comment by spiralhalo** [comment]
For now, please switch to unified. I can guide you to config unified in order to get the old "edition" that you need if you ask on the discord.

I can't tell you what issue this is, only if it's worth fixing or not based on how frequent it happens. Switching from Lumi HDR to PBR probably don't happen very often, and like I said you don't need to do that anymore since the unified edition merges HDR and PBR together. Only reopen this issue if it recurs in the unified edition, then I can try to pinpoint the cause.
