### ISSUE TITLE
Some options doesn't exist

### ISSUE THREAD

**Issue by wstar2022** [spiralhalo/LumiLights#74]
There is a key `"config.lumi_lights.value.reflection_oversampling"` in the language file `en_us.json`. But when I try to look for the option in other files, there's no such option.

Search result is in the picture below.

![result](https://user-images.githubusercontent.com/83652843/187110208-2679b19d-b468-4924-a6dc-c957499af48f.png)

**Comment by ambrosia13** [comment]
It's entirely possible that it's just an unused feature

**Comment by wstar2022** [comment]
I guess so.

**Comment by wstar2022** [comment]
I found another option that doesn't exist, named `"config.lumi_lights.value.lightrays_mode"`.

Search result is in the picture below.

![result](https://user-images.githubusercontent.com/83652843/187115521-7a1aed06-2520-4bb1-815c-9983d396d99e.png)

**Comment by spiralhalo** [comment]
Lumi Lights gains and loses features all the time so this is to be expected.

Specifically, when a new feature is added there will be a few options that come with it, but as the feature is refined I sometimes replaced options with magic constants.

I don't feel the need to remove these because they aren't causing any issues, and honestly I forgot most of them exist. I can remove them if you want though, don't think there is any need to keep them.

**Comment by wstar2022** [comment]
Okay, I got it. I hope that these missing options will be added one by one in the future. :)

#76
