### ISSUE TITLE
Entities appear too bright

### ISSUE THREAD

**Issue by Reeses-Puffs** [spiralhalo/LumiLights#8]
I was playing on an SMP and I noticed that darker colored entities, namely spiders and endermen, appeared to be very bright.

**Comment by Reeses-Puffs** [comment]
![2020-12-07_16 41 25](https://user-images.githubusercontent.com/73549793/101664543-f8eff180-3a19-11eb-83b9-70272d3dbd46.png)
![2020-12-07_16 41 44](https://user-images.githubusercontent.com/73549793/101664583-04dbb380-3a1a-11eb-913b-7284ea2e3c92.png)
![2020-12-07_21 16 46](https://user-images.githubusercontent.com/73549793/101664604-0ad19480-3a1a-11eb-87b2-effd26de4d25.png)

**Comment by spiralhalo** [comment]
Commit 56a31f70152911d192d8df530d639e9972c16ff9 just seem to fix this, but I can't explain this behavior. I will mark is as resolved for the time being and open another issue when I found the root cause.

**Comment by spiralhalo** [comment]
The root cause seem to be F0 as expected.

F0--determined by index of refraction--represents base reflectivity which is assumed to be 0.04 for non-metals.

In reality each material has different base reflectivity which is too complicated to define individually. I thought 0.04 was low enough to not matter but it seem to cause every dark objects to appear too bright, including blocks.

The problem now is that I don't really know if this is an issue. For example, we don't know the index of refraction of Endermen skin to begin with. F0 wasn't supposed to be a controllable parameter unlike roughness and metallic. Though since I already made an assumption, I will probably make a different assumption that a material's F0 is affected by their texture brightness. Should work to fix the dark object problem at least.

**Comment by spiralhalo** [comment]
I still can't explain why 56a31f70152911d192d8df530d639e9972c16ff9 fixed it though.

**Comment by spiralhalo** [comment]
It looks like 56a31f70152911d192d8df530d639e9972c16ff9 fixed a completely different problem (which I still don't understand, by the way). I have opened #11 for base reflectivity related issue if anyone is interested.
